version: 2
models:
  - name: dim_listings_cleansed
    description: Cleansed Dim Table which contains information about listing.
    columns:
      - name: listing_id
        data_type: number
        description: listing_id is primary key , should be unique and not null
        tests:
          - unique
          - not_null

      - name: host_id
        description: host_id is reference key , shoul be present in dim_hosts_cleansed and not more than 25 null count 
        tests:
          - not_null:
              severity: warn
              error_if: ">25"
              warn_if: ">5"

          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: roo_type must be in given three values
        tests:
          - accepted_values:
              values: [ 'Entire home/apt' , 'Private room']

      - name: price
        description: price should be greater than 0
        tests:
          - test_check_positive_value

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'


  - name: dim_host_cleansed
    columns:
      - name: host_id
        data_type: number
        description: host_id is primary key , should be unique and not null
        tests:
          - unique
          - not_null

  - name: fct_reviews
    columns:
      - name: review_date
        description: review_date should not be null
        tests:
          - not_null

      - name: REVIEW_SENTIMENT
        description: REVIEW_SENTIMENT should not be nullof 3 types only
        tests:
          - accepted_values:
              values: [ 'positive' , 'negative','neutral']

      - name : review_id
        description: surrogate key to identify the unique records in fct_reviews table
        tests:
          - unique 

