version: 2
models:
  - name: dim_listings_cleansed
    description: 'dim listing cleansed table contains goibibo listing info'
    columns:
      - name: listing_id
        description: 'Primary key for the listing'
        tests:
          - unique
          - not_null:
              severity: warn
              error_if: '>5'
              warn_if: '>8'

      # - name: minimum_nights
      #   description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
      #   tests:
      #     - check_min_night_more_than_1k

      - name: host_id
        description: 'Host id columns info'
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
