version: 2
models:
  - name: dim_listings_cleansed_latest
    description: Cleansed Dim Table which contains information about listing.
    columns:
      - name: listing_id
        data_type: number
        description: listing_id is primary key , should be unique and not null
        tests:
          - unique
          - not_null

      - name: host_id
        description: host_id is reference key , shoul be present in dim_hosts_cleansed and not more than 25 null count 
        tests:
          - not_null:
              severity: warn
              error_if: ">25"
              warn_if: ">5"

          - relationships:
              to: ref('dim_hosts_cleansed_latest')
              field: host_id

      - name: room_type
        description: roo_type must be in given three values
        tests:
          - accepted_values:
              values: [ 'Entire home/apt' , 'Private room']

      - name: price
        description: price should be greater than 0
        tests:
          - test_check_positive_value

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'

      - name: listing_name
        description: name of the listing

      - name: created_at
        description: date on which listing was created

      - name: updated_at
        description: date on which listing was updated


  - name: dim_hosts_cleansed_latest  
    description: cleaned host table having information about host
    columns:
      - name: host_id
        data_type: number
        description: host_id is primary key , should be unique and not null
        tests:
          - unique
          - not_null
      
      - name: host_name
        description: name of the host 

      - name: is_superhost
        description: check whether host is superhost or not , t means superhost 

      - name: region
        description: particular region where preorty belongs to eg , UK , europe , asia

  - name: fct_reviews
    description: Fact tables containing all reviews corresponding to listings
    columns:
      - name: review_date
        description: review_date should not be null
        tests:
          - not_null

      - name: REVIEW_SENTIMENT
        description: REVIEW_SENTIMENT should not be nullof 3 types only
        tests:
          - accepted_values:
              values: [ 'positive' , 'negative','neutral']

      - name : review_id
        description: surrogate key to identify the unique records in fct_reviews table and hsould not be null
        tests:
          - not_null

      - name : listing_id
        description: reference from the table dim_listings_cleansed_latest

  - name: fct_reviews_host_list 
    description: Fact tables containing all reviews corresponding to listings and host information
    columns:
      - name: sr_key
        description: surrogate key generated to identify unique records

      - name: listing_id
        description: listing id reference from dim_listings_table

      - name : host_id
        description: host_id reference from dim_hosts_table

  - name: vw_hosts_cleansed 
    description: view holding latest information , with cleansed and dq check
    columns:
      - name: dq_check
        description: value is either true or false , true will move to dim tables and false will be moved to suspended entry table
        
  - name: vw_listings_cleansed 
    description: view holding latest information , with cleansed and dq check
    columns:
      - name: dq_check
        description: value is either true or false , true will move to dim tables and false will be moved to suspended entry table
        
  - name: vw_reviews_cleansed 
    description: view holding latest information , with cleansed and dq check
    columns:
      - name: dq_check
        description: value is either true or false , true will move to dim tables and false will be moved to suspended entry table
  
  - name: suspended_raw_entry 
    description: all the invalid records will be moved to this table for further investigation
    columns:
      - name: json_records
        description: the json of the entire record to indetify the root cause 
        
  - name: raw_hosts_toprocess  
    description: hold the current data during pipeline from stream , will be truncate after run completed
    
  - name: raw_listings_toprocess  
    description: hold the current data during pipeline from stream , will be truncate after run completed
    
  - name: raw_reviews_toprocess  
    description: hold the current data during pipeline from stream , will be truncate after run completed