version: 2

sources:
  - name: source_name_goibibo
    database: DB_VN252_PM  
    schema: raw
    tables:

      - name: hosts_stream
        identifier: raw_hosts_live_stream
        description: stream raw_hosts_live_stream based on table raw.raw_hosts_live

      - name: listing_stream
        identifier: RAW_LISTING_LIVE_STREAM

      - name: reviews_stream
        identifier: raw_reviews_live_stream
        loaded_at_field: date
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 4444, period: day}
